name: CI

on:
  push:
    branches: [stable, develop]
  pull_request:
    branches: [stable, develop]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.repository == 'noaa-oar-arl/monet'
    strategy:
      matrix:
        python-version: ["3.6", "3.8", "3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python (micromamba)
        uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: environment-dev.yml
          cache-env: true
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Test with pytest
        run: pytest -n auto -v
